### ISSUE TITLE
finish data summary tab

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/datapie#12]
includes data table summary and report download button

**Comment by sheilasaia** [comment]
see knitr document development made by @jhp7e @CoastalPlainSoils @alesiahallmark @vanderbi @atn38

**Comment by wetlandscapes** [comment]
For some reason the summary tab does not include all columns in a data set. @ktoddbrown, I think you might have wrote that code. Any chance you could look over it?

**Comment by clnsmth** [comment]
Hi @atn38, a friendly reminder that re-titling this issue changes it's scope and meaning within the project and possibly creates confusion. The new title implies #32, and thus duplicates an issue, which we want to avoid. Additionally, the original scope of this issue addressed a core feature of the app that the team agreed to implementing before adding the enhancement of integrating the static report into the UI. I strongly suggest we focus on realizing the core components of the project before perusing enhancements.

**Comment by sheilasaia** [comment]
related to issue #23.

**Comment by clnsmth** [comment]
A clarifying question: This issue is related to the "Overall Data Table Report" of the "Summary Report" tab?
