### ISSUE TITLE
data summary tab specialized selection for column variable

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/datapie#13]
talk to @alesiahallmark for more thoughts on this.

**Comment by atn38** [comment]
mock-up as requested @sheilasaia!

![image](https://user-images.githubusercontent.com/42045942/60035265-0a9cd800-9672-11e9-84e4-78b0771dac00.png)

**Comment by sheilasaia** [comment]
Awesome, @atn38! Thank you for doing this. Maybe you, @wetlandscapes, and I can chat about how to make this work? We'd have to figure out how to figure out how to infer which summary report to choose based on their selection...which I think we'd need to get more info about before we can implement. @clnsmth, can you bring this up at our meeting this week?

**Comment by atn38** [comment]
It'd be awesome if you and @wetlandscapes can spare some time. Regardless
of how the data summary tab will look at this stage -- two options **(1.)**
Generate the complete HTML report, put that in an iframe for in-GUI display
(see #32), and include a download button, or **(2.)** Like the Paint mockup
above -- there's still the question of how to get the data+metadata list
objects once it is ingested to pass into the static report functions. To
that end I started looking into the GUI source code, and have a better idea
of what questions to ask compared to last week.

**Comment by atn38** [comment]
The app has moved enough away from this direction at this point, so I'm closing this.
