### ISSUE TITLE
fix relevant variables for x and y axes selection

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/datapie#16]
right now the x and y axes selection only allow continuous variables but it'd be nice to have, for example, histograms that allow character and factor variables

**Comment by sheilasaia** [comment]
@ktoddbrown what's the status on this? are you thinking you'll include other variable types as well?

**Comment by sheilasaia** [comment]
@lkuiucsb do you want to take this over? i think it pertains to the issue we talked about today at the meeting (i.e., that we current can't plot some types of variables).

**Comment by lkuiucsb** [comment]
Sure. I can work on this one. I think once we fix the other issue, hopefully this will be fixed too.

**Comment by sheilasaia** [comment]
@lkuiucsb what's the status on this? let me know if you need help.

**Comment by lkuiucsb** [comment]
I am on a week-long meeting this week. Probably don’t have time to get to it until later next week. If you have time, go ahead and edit it. I will check in with you later once I have time. @sheilasaia

**Comment by sheilasaia** [comment]
@ktoddbrown do you want to work on this instead?

**Comment by lkuiucsb** [comment]
This seems to be no problem in the Kui-development branch. So I am going to close this one unless you see more issues later.
