### ISSUE TITLE
Copy data package to user specified directory (GUI feature)

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/datapie#23]
Use the function `data_package_copy()` to copy the data package contents to a user specified directory when the user clicks the "download data package" button.

**Comment by clnsmth** [comment]
@sheilasaia and @wetlandscapes, is this issue still open?

**Comment by sheilasaia** [comment]
add download data button to raw data tab (left panel).

**Comment by sheilasaia** [comment]
@clnsmth, @atn38, @wetlandscapes - is this issue and #12 still open?

**Comment by wetlandscapes** [comment]
I think so.

**Comment by clnsmth** [comment]
I'm working on this now.

**Comment by clnsmth** [comment]
This feature has been implemented in the 'Raw Data' tab under the 'Fetch data from DOI' radio button. Once a DOI has been fetched, click 'Save Data' and a file browser will pop-up. Select the directory in which you'd like to save the data package and voila! The data package has been saved there.
