### ISSUE TITLE
Create vignettes

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/datapie#26]
I have three vignettes in mind to demonstrate use of our app:

1.) Overview - What the project is and how it improves exploration of data repo contents, as well as the two general features of the app (static and interactive reports).
2.) Static report - What it is, why use it, and how to create it.
3.) Interactive report - What it is, why use it, and how to use it.

Once the app is working, I'll draft these up and send out for a round of comments/edits.

**Comment by CoastalPlainSoils** [comment]
I'm happy to help you on the verbal description/purpose of things as well for the vignettes. Just let me know :)

**Comment by clnsmth** [comment]
Thanks for offering to help @CoastalPlainSoils. Would you like to lead this issue?

**Comment by clnsmth** [comment]
FYI @CoastalPlainSoils, the project metadata and website is built using R packages `codemetar`, `devtools` and  `pkgdown`. General workflow is:

```
# Update codemeta version of package metadata
codemetar::write_codemeta()

# Update function documentation and other package metadata
devtools::document()

# Update website
pkgdown::build_site()
```

You'll then need to commit these changes and push to the repo.

**Comment by CoastalPlainSoils** [comment]
@clnsmth Awesome thank you, I plan to work on this Tuesday evening.

**Comment by sheilasaia** [comment]
Note to selves...import these vignettes into about tab!

**Comment by clnsmth** [comment]
Working on this now at branch `fix_26`.

**Comment by clnsmth** [comment]
Done (see 57999e7ce7cd3842206b9cd964a169d7a26079e3). 

NOTE: Screen shots will have to be updated prior to production release.
