### ISSUE TITLE
Improved handling of download location in data_package_download

### ISSUE THREAD

**Issue by wetlandscapes** [IMCR-Hackathon/datapie#28]
I've been playing around with the functionalities of using `data_package_download` and `data_package_read`. When the data.pkg.path is NULL, the two packages play well together, as they download to a controlled location in the temp directory, with a known folder prefix (i.e., '/data_package'). However, if the user specifies a different directory then (e.g., the download.dir argument is not NULL) then `data_package_read` does not read the correct file.

For example, the code below works as expected:
```
data_package_download("doi:10.6073/pasta/7ced32c47c7f3eb31cf48606b1501cde")
data_package_read()
```

This code, however, returns an error (assuming you have a C:/Projects folder):
```
data_package_download("doi:10.6073/pasta/7ced32c47c7f3eb31cf48606b1501cde",  "C:/Projects")
data_package_read("C:/Projects")
```

__Expected behavior__: I would have expected we'd be able to download to a custom directory and be able to pass that directory to `data_package_read` without problems.

__Suggested solution__: Append a suffix the download.dir. Namely, use the same structure as with the temporary directory: `download.dir <- paste0(download.dir, '/data_package')`.

Thoughts?

**Comment by clnsmth** [comment]
Thanks for bringing this feature to discussion @wetlandscapes. Below is an example of how the `data_package_download()` and `data_package_read()` functions work together.

```
# Download data package to the parent directory "data_packages", a directory 
# where several data packages may eventually be downloaded.
data_package_download(
  data.pkg.doi = 'doi:10.18739/A2DP3X',
  download.dir = 'C:\\Users\\Colin\\Desktop\\data_packages'
)

# The "data_package" directory now contains a directory named after the data package DOI.
# that was just downloaded. At this point the user can rename this directory to a more human 
# readable form if they want to. View directory contents of the downloaded data package ...
dir('C:\\Users\\Colin\\Desktop\\data_packages\\doi_10.18739_A2DP3X')

# Like `metajam::read_d1_files()`, `data_package_read()` requires a path to the data package directory # containing the sub-directories of each data object ...
data <- data_package_read(
  data.pkg.path = 'C:\\Users\\Colin\\Desktop\\data_packages\\doi_10.18739_A2DP3X'
)

# The content is read into the expected list structure.
# View data package contents ...
View(data)

# Clean up
data_package_remove('C:\\Users\\Colin\\Desktop\\data_packages\\doi_10.18739_A2DP3X')
```

I think the main issue here is deciding whether to download data packages to sub-directories of a user specified parent directory (the current implementation) or to download the data package to the specific directory specified by `data.package.path` of the `data_package_download()` function (as you propose). I choose the former as a matter of preference/familiarity, but then again I can be a bit obtuse when it comes to the common use case.

Perhaps just a matter of clearly communicating this in the documentation? Additional, thoughts?

**Comment by clnsmth** [comment]
@wetlandscapes, may I close this issue?

**Comment by clnsmth** [comment]
Is this still and issue @wetlandscapes?

**Comment by clnsmth** [comment]
I'm working on this now.
