### ISSUE TITLE
add doi download code block to "r-code" tab

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/datapie#30]
just an idea, what do you think @wetlandscapes?

**Comment by wetlandscapes** [comment]
Great idea! Looks like that bit of code is in the `server.R`  file under the "GENERATE R-CODE FOR OUTPUT" section.

If you wanted to get fancy, I bet you could use regex or `stringi`/`stringr` to replace the code generated with `string_code` to add the actual name of the R objects that would be relevant to the user.

**Comment by sheilasaia** [comment]
@wetlandscapes I like that idea! Going to work on it next. I want to fill in the selected file name and the doi for sure.
