### ISSUE TITLE
data_package_download and long file paths

### ISSUE THREAD

**Issue by atn38** [IMCR-Hackathon/datapie#40]
`data_package_download` gives this warning when used with this DOI `doi:10.6073/pasta/ef77fb0348fc0d31e7d3875c947aaa4e`

```
Warning messages:
1: In file.copy(from = pkg_dir_name, to = parent_dir, recursive = TRUE) :
  over-long path length
```

End results is only data file gets copied over to directory specified in `download.dir` argument while metadata files -- whose names are longer -- do not make it. This is probably a Window-specific issue (260 characters limit to file paths). 

If I use `metajam::download_d1_pkg` directly, both data and metadata are there. The file paths generally are shorter with this option.

Using `data_package_download`, file paths work out to be: `download.dir/https_pasta.lternet.edu_package_metadata_eml_knb-lter-ntl_364_1/https_pasta.lternet.edu_package_metadata_eml_knb-lter-ntl_364_1__LakeMendota_SpatialSurfaceChemistry__csv`

**Comment by clnsmth** [comment]
Thanks for reporting this issue @atn38. Let me think about this a bit more. It may be that the directory and file naming conventions should change in `metajam` since those outputs are not much less verbose than those of `data_package_download()`.

**Comment by clnsmth** [comment]
Hi @atn38. I've shortened file paths by:
1.) Removing the DOI from `metajam` named data object directories and the data objects themselves. To access this new feature you will have to update your version of `metajam` (i.e. `remotes::install_github('clnsmth/metajam')`.
2.) Abbreviated parent data package directories when downloading to a users computer. This feature is effective as of b6512aad

I'll raise this issue with the `metajam` project and suggest an alternative naming scheme that is less verbose.

One additional measure we could take to shorten path length is to reduce the `paste0(tempdir(), '/data_packages')` directory to `paste0(tempdir(), '/pkg')`. Any objections @wetlandscapes or @atn38?

**Comment by sheilasaia** [comment]
@clnsmth and @wetlandscapes I'm noticing that the file names are now showing up strange in the up-to-date version of the development branch app. I'm just jumping into this conversation but will try to work on fixing this issue. Pasting my view below:

<img width="520" alt="Screen Shot 2019-06-25 at 10 23 39 AM" src="https://user-images.githubusercontent.com/12959101/60106688-a04c6c00-9733-11e9-858d-7536fbc21a47.png">

**Comment by sheilasaia** [comment]
@clnsmth proposed a method at the bottom of the data_package_shiny_handler.R function (see commit cded7d5)

**Comment by clnsmth** [comment]
This is odd behavior @sheilasaia. I'm not sure what's going on inside the GUI, but the data object being passed to it by `data_package_read()` hasn't changed. Please make sure you have the correct version of metajam installed (i.e. `remotes::install_github('clnsmth/metajam') and the most recent versions of `data_package_download()` and `data_package_read()` from the master branch.

**Comment by sheilasaia** [comment]
@clnsmth i'll try updating my metajam package as you suggested and see if the issue persists.

**Comment by sheilasaia** [comment]
@clnsmth, i just reinstalled your version of metajam and am still seeing long path names in the gui. that is, my photo above still applies and it's hard to know what dataset your picking because the file name gets cut off. @wetlandscapes and @lkuiucsb are you seeing this too when you load data from a doi?

i'm asking about this because i'll need to pass them to the r-code tab. i have some code that i think might fix it so let me know if you want me to send it your way.

**Comment by lkuiucsb** [comment]
I have different view here. On my screen, it shows short file name instead of long one as shown in your photo above). However, I was using this DOI as an example: doi:10.6073/pasta/ef77fb0348fc0d31e7d3875c947aaa4e. What DOI do you use? I am wondering if it has something to do with some particular data package.

**Comment by lkuiucsb** [comment]
I do want to add an issue here. The files in this doi do not shown in "select file" list. Try this out:  doi:10.6073/pasta/be54fff488ec4d0d6146956b5fff057e

After downloading the files from DOI (seems to work fine), the file names did not pass to the "select file". Instead, the example data was shown in the "select file" list.

**Comment by sheilasaia** [comment]
i want to correct my previous comment. i don't actually need the shorted named for the r-code tab but am having this issue on the data summary tab with this doi:  doi:10.6073/pasta/b745934d136ce9ca8de26c5063eee86a (Jason posted this as an example a while back, there are three files to select from).

**Comment by lkuiucsb** [comment]
@sheilasaia I think there might be something to do with the package update. Here is my screenshot:
![Untitled](https://user-images.githubusercontent.com/20977133/61092902-09eb9c00-a3fd-11e9-9c71-b730b8a7a0d6.png)

**Comment by sheilasaia** [comment]
@lkuiucsb ahh ok maybe i'll try reinstalling again...so weird!

**Comment by sheilasaia** [comment]
yay! works for me now! @clnsmth and @atn38, can we close this now?
