### ISSUE TITLE
how to launch app (before packaging)

### ISSUE THREAD

**Issue by lkuiucsb** [IMCR-Hackathon/datapie#52]
For all your guys, in case you haven't had chance to try this app, here is the start up script, before launching the package. 

Here we go (please change the file path accordingly):

library(ggplot2)
library(shiny)
library(shinyjs)
library(readxl)
library(haven)
library(RColorBrewer)
library(plotly)
library(stringr)
library(readr)
library(usethis)

sapply(list.files(pattern=".R", path="../Github/ggplotgui/R", full.names=TRUE), source)
load("../Github/ggplotgui/data/data_example.rda")
CleverName_shiny()

**Comment by sheilasaia** [comment]
if running in an R project environment, you can change the file paths so they are relative to the .Rproj file in the ggplotgui directory.

**Comment by clnsmth** [comment]
No need for this procedure any more since the project can now be installed as a package. See #46.
