### ISSUE TITLE
Package build: Stale URLs

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/datapie#55]
@wetlandscapes, @sheilasaia - URLs in `datapie_shiny.R` (formerly `CleverName_shiny.R`) point to the originators GitHub (e.g. line 220) or what appears to be the originators ShinyServer (e.g. line 227). Please update these for our project.

**Comment by sheilasaia** [comment]
@clnsmth this tab is going to be replaced with info on the edi hackathon so it shouldn't be an issue once we draft something that we want to include about the hackathon goals and our motivation for this project. do you or @vanderbi want to draft something and I can add it in?

**Comment by clnsmth** [comment]
Thanks for the clarification @sheilasaia. 

Regarding EDI attribution, I recommend adding this to the project level README.md (the common practice), which would circumvent the need to take valuable real-estate in the UI where this information is not particularly useful.

**Comment by clnsmth** [comment]
#63 closes this issue.
