### ISSUE TITLE
enable user upload of personal dataset into gui

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/datapie#57]

**Comment by CoastalPlainSoils** [comment]
Yes this would be so useful!!!!

**Comment by clnsmth** [comment]
Working on this now at branch **fix_57**.

**Comment by clnsmth** [comment]
All datapie functionality,  except the summary report, has been extended to local data files.

**Comment by atn38** [comment]
report generation for user-uploaded data is now in place in fix_57

**Comment by clnsmth** [comment]
Nice @atn38!
