### ISSUE TITLE
about tab: needs to be updated to include info on edi and the hackathon

### ISSUE THREAD

**Issue by sheilasaia** [IMCR-Hackathon/datapie#63]
right now the about tab includes info from the ggplotgui so it needs to be updated to include information on the hackathon. i will brainstorm something and ask for feedback here.

**Comment by clnsmth** [comment]
Related to #55?

**Comment by sheilasaia** [comment]
@clnsmth yeah i suppose it's related to #55. I'll close this one and you close that one! ;)
