### ISSUE TITLE
Error message when DOI is not valid

### ISSUE THREAD

**Issue by atn38** [IMCR-Hackathon/datapie#72]
If an invalid DOI is entered, the user is not alerted and the "select data object" menu is populated with the sample data. See GIF below. I used `doi:10.1016/S2214-109X(18)30456-X`, which is an article. A more common mistake might be to input a data package DOI not available on DataOne.

![invalid_doi](https://user-images.githubusercontent.com/42045942/62804144-0443ad80-bab2-11e9-9a94-678174696f45.gif)

**Comment by atn38** [comment]
Another instance where the data ingestion fails silently is where a data package DOI is available through DataOne, but have a metadata standard other than EML. (`metajam` only ingests EML metadata at the moment). Example: `doi:10.1575/1912/bco-dmo.652124`.

**Comment by clnsmth** [comment]
Working on this now at branch fix_72.

**Comment by clnsmth** [comment]
Done (see b45c2f54e8bdbcb6b85d830fb7f4d3d1a6244dea).
