### ISSUE TITLE
refactor/rework some components of summary report

### ISSUE THREAD

**Issue by atn38** [IMCR-Hackathon/datapie#75]
These components are originally code written by @jhp7e and @CoastalPlainSoils, so with your permission I'd like to refactor this codebase to address some inconsistencies (see example below) and improve code for best practices (style, argument defs, documentation etc) in anticipation of the beta-release.

Example bug: One function (`SummaryTable3()`) detects no categorical variables, but the subsequent function to be called in the report (`SummaryTable2()`) does detect some categorical variables and their levels. 

![image](https://user-images.githubusercontent.com/42045942/62884551-78719180-bcfc-11e9-819a-be497ad5a531.png)

**Comment by atn38** [comment]
This is ongoing. Some aspects I've done so far:
- Added Roxygen comments to these functions. 
- Add or remove functions from exports as I think is appropriate.
- Rename arguments or refactor functions to use different arguments similar to `datapie`'s other functions.
- Rename some functions to be more clear at a glance.
- Work in these changes in the larger context (wrapper functions, report template)

**Comment by CoastalPlainSoils** [comment]
Sorry I've been busy with some research and things before the semester starts. Of course I am fine with you changing/editing the code I originally helped to author.
