### ISSUE TITLE
Issues Reading CSV Files with Headers

### ISSUE THREAD

**Issue by jhp7e** [IMCR-Hackathon/datapie#76]
There are several issues associated with files containing header lines (which should be skipped based on the numHeaderLines tag in EML). 

1) Data Tab: Reads in OK, but misinterprets header lines as data lines - so the column names are wrong. 

2) Report Tab: "**Error:** cannot open the connection" shows up when trying to generate the summary report on a PC for a file with headers.  

The error message seems to be related to mixed use of slashes when opening a file to report other problems. 

The console shows (note the mixed \ and / s in the file name that is failing to open): 
> Error : 
> Column `column_name` is unknown
> Warning in file(con, "r") :
>   cannot open file 'C:\Users\John\AppData\Local\Temp\Rtmpsh4zTY/reports_output/Error : Column `column_name` is unknown
> ': No such file or directory
> Warning: Error in file: cannot open the connection
>   [No stack trace available]

3) Plot and Interactive Plot Tabs: Get "Error: object '' '' not found"

**To Reproduce**
- [X ] via installing `datapie` and calling the function

_What DOI and data object did you encounter the bug with?_
DOI: 10.6073/pasta/b6f4417e85b275e6de6e45d3f509b6d6
Data object: marsh_elev.csv

**Expected behavior**
What did you expect to happen instead of the bug?

**Screenshots**
If applicable.

**Session Information**

> R version 3.6.0 (2019-04-26)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> Random number generation:
>  RNG:     Mersenne-Twister 
>  Normal:  Inversion 
>  Sample:  Rounding 
>  
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] ggplot2_3.2.1      shiny_1.3.2        datapie_0.0.0.9000
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.4.1         shinyFiles_0.7.3   tidyr_0.8.3        jsonlite_1.6      
>  [5] viridisLite_0.3.0  assertthat_0.2.1   askpass_1.1        highr_0.8         
>  [9] dataone_2.1.2      cellranger_1.1.0   yaml_2.2.0         remotes_2.1.0     
> [13] pillar_1.4.2       backports_1.1.4    glue_1.3.1         uuid_0.1-2        
> [17] digest_0.6.20      RColorBrewer_1.1-2 promises_1.0.1     redland_1.0.17-10 
> [21] EML_2.0.0          colorspace_1.4-1   htmltools_0.3.6    httpuv_1.5.1      
> [25] plyr_1.8.4         XML_3.98-1.20      pkgconfig_2.0.2    haven_2.1.1       
> [29] purrr_0.3.2        xtable_1.8-4       scales_1.0.0       processx_3.4.1    
> [33] later_0.8.0        emld_0.2.0         openssl_1.4.1      tibble_2.1.3      
> [37] withr_2.1.2        shinyjs_1.0        lazyeval_0.2.2     cli_1.1.0         
> [41] metajam_0.2.0.9000 magrittr_1.5       crayon_1.3.4       readxl_1.3.1      
> [45] mime_0.7           evaluate_0.14      ps_1.3.0           fs_1.3.1          
> [49] forcats_0.4.0      xml2_1.2.2         parsedate_1.2.0    pkgbuild_1.0.4    
> [53] tools_3.6.0        hash_2.2.6.1       data.table_1.12.2  prettyunits_1.0.2 
> [57] hms_0.5.0          stringr_1.4.0      plotly_4.9.0       V8_2.3            
> [61] munsell_0.5.0      callr_3.3.1        compiler_3.6.0     jqr_1.1.0         
> [65] rlang_0.4.0        grid_3.6.0         jsonld_2.1         rstudioapi_0.10   
> [69] htmlwidgets_1.3    crosstalk_1.0.0    datapack_1.3.1     labeling_0.3      
> [73] base64enc_0.1-3    rmarkdown_1.14     gtable_0.3.0       roxygen2_6.1.1    
> [77] curl_3.3           reshape2_1.4.3     R6_2.4.0           lubridate_1.7.4   
> [81] knitr_1.24         dplyr_0.8.3        zeallot_0.1.0      commonmark_1.7    
> [85] rprojroot_1.3-2    readr_1.3.1        stringi_1.4.3      Rcpp_1.0.2        
> [89] vctrs_0.2.0        tidyselect_0.2.5   xfun_0.8

**Comment by clnsmth** [comment]
Should probably implement this fix as a `metajam` enhancement.

**Comment by clnsmth** [comment]
Related to #34.

**Comment by atn38** [comment]
A pass at resolving this issue via enhancements to `metajam`: https://github.com/clnsmth/metajam/commit/60fcf2594f3699e77547a477dac9d52bcec65c6c.

Re-install `metajam` from @clnsmth's fork via `devtools::install_github("clnsmth/metajam")` to fix issue in your local copy of datapie.
