### ISSUE TITLE
Update UI aesthetics

### ISSUE THREAD

**Issue by clnsmth** [IMCR-Hackathon/datapie#84]
A general clean up of UI appearance (e.g. font type and size, plot dimensions, etc.).

**Comment by clnsmth** [comment]
Working on this now at branch fix_84.

**Comment by clnsmth** [comment]
Done for now (see eb592dcf3dd353b6b12db6be216a2cce1ba25c40). We'll likely make another pass at this before going to production.

**Comment by atn38** [comment]
would it make sense to add a "welcome" panel at the lower left on the Data tab, beneath the "Data loading options"? It's the first thing people see. Super condensed information: here are the three main things we offer (report, plot, interactive plot), maximize app window for best visuals. Ok, this is motivated mostly by the latter point, but having a two-liner orientation on the landing might be good.

**Comment by clnsmth** [comment]
IMO if the UI design doesn’t inherently communicate this info, then it is too complex and needs simplification. A user should be presented with an intuitive UI requiring minimal direction.

How about adding this text at the top of the Help tab?

On Fri, Oct 11, 2019 at 14:41 An T. Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:

would it make sense to add a "welcome" panel at the lower left on the Data tab, beneath the "Data loading options"? It's the first thing people see. Super condensed information: here are the three main things we offer (report, plot, interactive plot), maximize app window for best visuals. Ok, this is motivated mostly by the latter point, but having a two-liner orientation on the landing might be good.
